const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s); const money=n=>'฿'+Number(n||0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
const categories=['รายได้ค่าบริการ','รายได้อื่น','เงินเดือน/ค่าจ้าง','ค่าเช่า','ค่าน้ำ/ไฟ/อินเทอร์เน็ต','วัสดุสำนักงาน','ค่าเดินทาง/ขนส่ง','ค่าซ่อมบำรุง','ค่าบริการวิชาชีพ','ภาษี/ค่าธรรมเนียม','ค่าเลี้ยงรับรอง/ประชุม','ซื้อสินทรัพย์','อื่น ๆ'];
let tx=JSON.parse(localStorage.getItem('office_tx')||'[]'), debts=JSON.parse(localStorage.getItem('office_debts')||'[]'), travels=JSON.parse(localStorage.getItem('office_travels')||'[]');
let funds=JSON.parse(localStorage.getItem('office_funds')||'[]'), people=JSON.parse(localStorage.getItem('office_people')||'[]'), templates=JSON.parse(localStorage.getItem('office_templates')||'[]'), trash=JSON.parse(localStorage.getItem('office_trash')||'[]'), audit=JSON.parse(localStorage.getItem('office_audit')||'[]');
let currentUser=localStorage.getItem('office_user')||'ผู้ใช้งานเครื่องนี้';
const save=()=>{localStorage.setItem('office_tx',JSON.stringify(tx));localStorage.setItem('office_debts',JSON.stringify(debts));localStorage.setItem('office_travels',JSON.stringify(travels));localStorage.setItem('office_funds',JSON.stringify(funds));localStorage.setItem('office_people',JSON.stringify(people));localStorage.setItem('office_templates',JSON.stringify(templates));localStorage.setItem('office_trash',JSON.stringify(trash));localStorage.setItem('office_audit',JSON.stringify(audit))};
function logAudit(action,item,detail=''){audit.unshift({id:Date.now()+Math.random(),at:new Date().toISOString(),user:currentUser,action,item,detail});audit=audit.slice(0,1000);save()}
function softDelete(kind,item){trash.unshift({id:Date.now()+Math.random(),kind,item,deletedAt:new Date().toISOString()});logAudit('ลบเข้าถังขยะ',kind,item.detail||item.mission||item.name||'');save()}
function nextDoc(prefix){let d=new Date(), ym=String(d.getFullYear()+543).slice(-2)+String(d.getMonth()+1).padStart(2,'0'),n=tx.filter(x=>(x.docno||'').startsWith(prefix+'-'+ym)).length+1;return `${prefix}-${ym}-${String(n).padStart(4,'0')}`}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
const titles={dashboard:['ภาพรวม','สรุปสถานะการเงินของสำนักงาน'],add:['เพิ่มรายการ','บันทึกรายรับหรือรายจ่ายได้อย่างรวดเร็ว'],history:['ประวัติรายการ','ค้นหาและดูข้อมูลย้อนหลัง'],debts:['ลูกหนี้–เจ้าหนี้','ติดตามยอดที่ต้องรับและต้องจ่าย'],travel:['เบิกเงินไปราชการ','บันทึกและตรวจสอบค่าใช้จ่ายในการเดินทาง'],manage:['จัดการระบบ','งบประมาณ บุคลากร แม่แบบ ตรวจสอบ และถังขยะ'],settings:['ตั้งค่า','สำรอง นำเข้า และจัดการข้อมูล']};
function showPage(id){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('#title').textContent=titles[id][0];$('#subtitle').textContent=titles[id][1];render()}; window.showPage=showPage;
$$('nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function render(){renderDashboard();renderHistory();renderDebts();renderTravels();renderManage();refreshTravelOptions()}
function renderDashboard(){let now=new Date(), ym=now.toISOString().slice(0,7), inc=tx.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0), exp=tx.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0), m=tx.filter(x=>x.date.slice(0,7)===ym), mi=m.filter(x=>x.type==='income'),me=m.filter(x=>x.type==='expense');$('#balance').textContent=money(inc-exp);$('#monthIncome').textContent=money(mi.reduce((a,x)=>a+x.amount,0));$('#monthExpense').textContent=money(me.reduce((a,x)=>a+x.amount,0));$('#incomeCount').textContent=mi.length+' รายการ';$('#expenseCount').textContent=me.length+' รายการ';$('#monthCount').textContent=m.length;let rec=[...tx].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id).slice(0,6);$('#recent').innerHTML=rec.length?rec.map(x=>`<div class="recent-item"><div class="icon ${x.type==='expense'?'exp':''}">${x.type==='income'?'↓':'↑'}</div><div><b>${esc(x.detail||x.category)}</b><small>${dateTH(x.date)} · ${esc(x.category)}</small></div><b class="${x.type==='income'?'income':'expense'}">${x.type==='income'?'+':'−'}${money(x.amount)}</b></div>`).join(''):'<div class="empty">ยังไม่มีรายการ</div>';renderChart()}
function renderChart(){let now=new Date(), arr=[];for(let i=5;i>=0;i--){let d=new Date(now.getFullYear(),now.getMonth()-i,1),ym=d.toISOString().slice(0,7),rows=tx.filter(x=>x.date.slice(0,7)===ym);arr.push({label:d.toLocaleDateString('th-TH',{month:'short'}),inc:rows.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0),exp:rows.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0)})}let max=Math.max(1,...arr.flatMap(x=>[x.inc,x.exp]));$('#chart').innerHTML=arr.map(x=>`<div class="bar-group"><div class="bars"><div title="รายรับ ${money(x.inc)}" class="bar" style="height:${x.inc/max*100}%"></div><div title="รายจ่าย ${money(x.exp)}" class="bar exp" style="height:${x.exp/max*100}%"></div></div><small>${x.label}</small></div>`).join('')}
function renderHistory(){let q=$('#search').value.toLowerCase(),typ=$('#filterType').value,mo=$('#filterMonth').value,rows=[...tx].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id).filter(x=>(typ==='all'||x.type===typ)&&(!mo||x.date.startsWith(mo))&&(!q||[x.detail,x.party,x.docno,x.category].join(' ').toLowerCase().includes(q)));$('#txRows').innerHTML=rows.map(x=>`<tr><td>${dateTH(x.date)}</td><td><span class="pill ${x.type==='expense'?'exp':''}">${x.type==='income'?'รายรับ':'รายจ่าย'}</span></td><td><b>${esc(x.detail||'-')}</b><br><small>${esc(x.docno||'')}</small></td><td>${esc(x.category)}</td><td>${esc(x.party||'-')}</td><td class="${x.type==='income'?'income':'expense'}"><b>${x.type==='income'?'+':'−'}${money(x.amount)}</b></td><td><button class="delete" onclick="delTx(${x.id})">ลบ</button></td></tr>`).join('');$('#emptyHistory').style.display=rows.length?'none':'block'}
function renderDebts(){let ar=debts.filter(x=>x.type==='ar').reduce((a,x)=>a+x.amount,0),ap=debts.filter(x=>x.type==='ap').reduce((a,x)=>a+x.amount,0);$('#arTotal').textContent=money(ar);$('#apTotal').textContent=money(ap);let today=new Date().toISOString().slice(0,10);$('#debtRows').innerHTML=debts.map(x=>`<tr><td><span class="pill ${x.type==='ap'?'exp':''}">${x.type==='ar'?'ลูกหนี้':'เจ้าหนี้'}</span></td><td><b>${esc(x.name)}</b></td><td>${esc(x.detail||'-')}</td><td>${dateTH(x.due)}</td><td><b>${money(x.amount)}</b></td><td>${x.due<today?'<span class="pill exp">เกินกำหนด</span>':'<span class="pill">รอดำเนินการ</span>'}</td><td><button class="delete" onclick="delDebt(${x.id})">ลบ</button></td></tr>`).join('');$('#emptyDebt').style.display=debts.length?'none':'block'}
function delTx(id){if(confirm('ย้ายรายการนี้ไปถังขยะหรือไม่?')){let x=tx.find(x=>x.id===id);if(x)softDelete('transaction',x);tx=tx.filter(x=>x.id!==id);save();render();toast('ย้ายไปถังขยะแล้ว')}} window.delTx=delTx;function delDebt(id){if(confirm('ย้ายรายการนี้ไปถังขยะหรือไม่?')){let x=debts.find(x=>x.id===id);if(x)softDelete('debt',x);debts=debts.filter(x=>x.id!==id);save();render();toast('ย้ายไปถังขยะแล้ว')}} window.delDebt=delDebt;
$('#txForm').onsubmit=e=>{e.preventDefault();let type=$('input[name=type]:checked').value;let obj={id:Date.now(),type,date:$('#date').value,amount:Number($('#amount').value),category:$('#category').value,payment:$('#payment').value,detail:$('#detail').value,party:$('#party').value,docno:$('#docno').value||nextDoc(type==='income'?'REC':'PAY')};obj.department=$('#department').value;obj.project=$('#project').value;obj.vat=Number($('#vat').value||0);obj.wht=Number($('#wht').value||0);obj.note=$('#note').value;tx.push(obj);logAudit('สร้าง','ธุรกรรม',obj.docno+' '+(obj.detail||obj.category));save();e.target.reset();$('#date').value=new Date().toISOString().slice(0,10);toast('บันทึกรายการเรียบร้อย');showPage('dashboard')};
['search','filterType','filterMonth'].forEach(id=>$('#'+id).addEventListener('input',renderHistory));$('#addDebt').onclick=()=>{$('#debtDialog').showModal();$('#dueDate').value=new Date().toISOString().slice(0,10)};$('#saveDebt').onclick=e=>{e.preventDefault();if(!$('#debtName').value||!$('#dueDate').value||!$('#debtAmount').value)return;debts.push({id:Date.now(),type:$('#debtType').value,name:$('#debtName').value,detail:$('#debtDetail').value,due:$('#dueDate').value,amount:Number($('#debtAmount').value)});save();$('#debtForm').reset();$('#debtDialog').close();render();toast('เพิ่มรายการแล้ว')};

function calcTravel(){let h=Number($('#hotelRate').value||0)*Number($('#hotelDays').value||0),a=Number($('#allowRate').value||0)*Number($('#allowDays').value||0),t=h+a,b=Number($('#unitBalance').value||0)-t;$('#hotelTotal').textContent=money(h);$('#allowTotal').textContent=money(a);$('#claimTotal').textContent=money(t);$('#afterBalance').textContent=money(b);$('#afterBalance').className=b<0?'expense':'income';return{hotelTotal:h,allowTotal:a,total:t,after:b}}
function renderTravels(){let total=travels.reduce((a,x)=>a+x.total,0);$('#travelTotal').textContent=money(total);$('#travelCount').textContent=travels.length;let rows=[...travels].sort((a,b)=>b.start.localeCompare(a.start)||b.id-a.id);$('#travelRows').innerHTML=rows.map(x=>`<div class="travel-card"><div class="travel-top"><div><b>${esc(x.traveler)}</b><small>${dateTH(x.start)} – ${dateTH(x.end)}</small></div><strong>${money(x.total)}</strong></div><div class="travel-mission">${esc(x.mission)}</div><div class="travel-meta"><span>ที่มา: ${esc(x.fundSource)}</span><span>คงเหลือก่อนเบิก ${money(x.unitBalance)}</span><span>ที่พัก ${money(x.hotelRate)} × ${x.hotelDays} วัน = ${money(x.hotelTotal)}</span><span>เบี้ยเลี้ยง ${money(x.allowRate)} × ${x.allowDays} วัน = ${money(x.allowTotal)}</span><span class="${x.after<0?'expense':'income'}">คงเหลือหลังเบิก ${money(x.after)}</span></div><button class="delete" onclick="delTravel(${x.id})">ลบ</button></div>`).join('');$('#emptyTravel').style.display=rows.length?'none':'block'}
function delTravel(id){if(confirm('ย้ายรายการเบิกนี้ไปถังขยะหรือไม่?')){let x=travels.find(x=>x.id===id);if(x)softDelete('travel',x);travels=travels.filter(x=>x.id!==id);save();render();toast('ย้ายไปถังขยะแล้ว')}} window.delTravel=delTravel;
['hotelRate','hotelDays','allowRate','allowDays','unitBalance'].forEach(id=>$('#'+id).addEventListener('input',calcTravel));
$('#travelForm').onsubmit=e=>{e.preventDefault();let c=calcTravel();if($('#travelEnd').value<$('#travelStart').value){alert('วันที่สิ้นสุดต้องไม่ก่อนวันที่เริ่ม');return}let fund=funds.find(f=>f.name===$('#fundSource').value), used=fund?travels.filter(x=>x.fundSource===fund.name).reduce((a,x)=>a+x.total,0):0;if(fund&&used+c.total>fund.limit&&!confirm('ยอดนี้เกินวงเงินของแหล่งเงิน ต้องการบันทึกต่อหรือไม่?'))return;let obj={id:Date.now(),docno:'TRV-'+String(Date.now()).slice(-8),travelType:$('#travelType').value,traveler:$('#traveler').value,fundSource:$('#fundSource').value,fundAmount:Number($('#fundAmount').value||0),mission:$('#mission').value,start:$('#travelStart').value,end:$('#travelEnd').value,unitBalance:Number($('#unitBalance').value||0),hotelRate:Number($('#hotelRate').value||0),hotelDays:Number($('#hotelDays').value||0),hotelTotal:c.hotelTotal,allowRate:Number($('#allowRate').value||0),allowDays:Number($('#allowDays').value||0),allowTotal:c.allowTotal,total:c.total,after:c.after};travels.push(obj);logAudit('สร้าง','เบิกไปราชการ',obj.docno+' '+obj.traveler);save();e.target.reset();$('#travelStart').value=$('#travelEnd').value=new Date().toISOString().slice(0,10);calcTravel();render();toast('บันทึกการเบิกเรียบร้อย')};
$('#exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify({transactions:tx,debts,travels,funds,people,templates,trash,audit},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='office-account-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#importFile').onchange=e=>{let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);tx=d.transactions||[];debts=d.debts||[];travels=d.travels||[];funds=d.funds||[];people=d.people||[];templates=d.templates||[];trash=d.trash||[];audit=d.audit||[];save();render();toast('นำเข้าข้อมูลแล้ว')}catch{alert('ไฟล์ไม่ถูกต้อง')}};r.readAsText(e.target.files[0])};$('#clearBtn').onclick=()=>{if(confirm('ต้องการล้างข้อมูลทั้งหมดจริงหรือไม่? การกระทำนี้ย้อนกลับไม่ได้')){tx=[];debts=[];travels=[];funds=[];people=[];templates=[];trash=[];audit=[];save();render();toast('ล้างข้อมูลแล้ว')}};
function refreshTravelOptions(){let tv=$('#traveler'),fs=$('#fundSource'),ts=$('#templateSelect');if(tv){let v=tv.value;tv.innerHTML='<option value="">เลือกบุคลากร</option>'+people.map(x=>`<option>${esc(x.name)}</option>`).join('');tv.value=v}if(fs){let v=fs.value;fs.innerHTML='<option value="">เลือกแหล่งเงิน</option>'+funds.map(x=>`<option>${esc(x.name)}</option>`).join('');fs.value=v}if(ts){let v=ts.value;ts.innerHTML='<option value="">ไม่ใช้แม่แบบ</option>'+templates.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');ts.value=v}}
function fundUsed(name){return travels.filter(x=>x.fundSource===name).reduce((a,x)=>a+Number(x.total||0),0)}
function renderManage(){if(!$('#fundRows'))return;$('#fundCount').textContent=funds.length;$('#personCount').textContent=people.length;$('#templateCount').textContent=templates.length;$('#trashCount').textContent=trash.length;$('#fundRows').innerHTML=funds.length?funds.map(f=>{let u=fundUsed(f.name),pct=f.limit?Math.min(100,u/f.limit*100):0,cl=u>f.limit?'over':u>=f.limit*.8?'warn':'';return `<div class="manage-row"><div><b>${esc(f.name)}</b><small>ใช้ ${money(u)} / วงเงิน ${money(f.limit)} · คงเหลือ ${money(f.limit-u)}</small><div class="budget-meter"><i class="${cl}" style="width:${pct}%"></i></div></div><button class="delete" onclick="removeFund(${f.id})">ลบ</button></div>`}).join(''):'<div class="empty">ยังไม่มีแหล่งเงิน</div>';$('#personRows').innerHTML=people.length?people.map(x=>`<div class="manage-row"><div><b>${esc(x.name)}</b><small>${esc(x.position||'-')} · ${esc(x.unit||'-')} ${x.info?'· '+esc(x.info):''}</small></div><button class="delete" onclick="removePerson(${x.id})">ลบ</button></div>`).join(''):'<div class="empty">ยังไม่มีบุคลากร</div>';$('#templateRows').innerHTML=templates.length?templates.map(x=>`<div class="manage-row"><div><b>${esc(x.name)}</b><small>${esc(x.mission)} · ที่พัก ${money(x.hotel)} · เบี้ยเลี้ยง ${money(x.allow)}</small></div><button class="delete" onclick="removeTemplate(${x.id})">ลบ</button></div>`).join(''):'<div class="empty">ยังไม่มีแม่แบบ</div>';let health=[];tx.forEach(x=>{if(x.amount<0)health.push(['bad','ยอดติดลบ',x.docno||x.detail]);if(!x.docno)health.push(['warn','ไม่มีเลขเอกสาร',x.detail||x.category])});travels.forEach(x=>{if(x.end<x.start)health.push(['bad','ช่วงวันที่ผิด',x.traveler]);if(x.after<0)health.push(['bad','ยอดเบิกเกินเงินคงเหลือ',x.traveler]);if(!x.fundSource||!x.traveler)health.push(['warn','เอกสารเบิกไม่ครบ',x.mission])});let seen=new Set();tx.forEach(x=>{let k=[x.date,x.amount,x.detail].join('|');if(seen.has(k))health.push(['warn','อาจเป็นรายการซ้ำ',x.detail||x.category]);seen.add(k)});$('#healthRows').innerHTML=health.length?health.map(h=>`<div class="health-item ${h[0]}"><b>${h[1]}</b><small>${esc(h[2]||'')}</small></div>`).join(''):'<div class="health-item"><b>✓ ไม่พบความผิดปกติสำคัญ</b></div>';$('#auditRows').innerHTML=audit.slice(0,100).map(x=>`<tr><td>${new Date(x.at).toLocaleString('th-TH')}</td><td>${esc(x.user)}</td><td>${esc(x.action)}</td><td>${esc(x.item)}</td><td>${esc(x.detail||'')}</td></tr>`).join('');$('#trashRows').innerHTML=trash.length?trash.map(x=>`<div class="manage-row"><div><b>${x.kind==='travel'?'เบิกไปราชการ':x.kind==='debt'?'ลูกหนี้/เจ้าหนี้':'ธุรกรรม'}</b><small>${esc(x.item.detail||x.item.mission||x.item.name||x.item.docno||'')} · ลบ ${new Date(x.deletedAt).toLocaleString('th-TH')}</small></div><div class="trash-actions"><button class="mini restore" onclick="restoreTrash('${x.id}')">กู้คืน</button><button class="mini hard-delete" onclick="purgeTrash('${x.id}')">ลบถาวร</button></div></div>`).join(''):'<div class="empty">ถังขยะว่าง</div>'}
$('#fundForm').onsubmit=e=>{e.preventDefault();let name=$('#fundName').value.trim(),limit=Number($('#fundLimit').value);if(funds.some(x=>x.name===name)){alert('มีแหล่งเงินชื่อนี้แล้ว');return}funds.push({id:Date.now(),name,limit});logAudit('สร้าง','แหล่งเงิน',name+' '+money(limit));e.target.reset();save();render()};
$('#personForm').onsubmit=e=>{e.preventDefault();let o={id:Date.now(),name:$('#personName').value.trim(),position:$('#personPosition').value,unit:$('#personUnit').value,info:$('#personInfo').value};people.push(o);logAudit('สร้าง','บุคลากร',o.name);e.target.reset();save();render()};
$('#templateForm').onsubmit=e=>{e.preventDefault();let o={id:Date.now(),name:$('#tplName').value,mission:$('#tplMission').value,hotel:Number($('#tplHotel').value||0),allow:Number($('#tplAllow').value||0)};templates.push(o);logAudit('สร้าง','แม่แบบ',o.name);e.target.reset();save();render()};
$('#templateSelect').onchange=e=>{let t=templates.find(x=>String(x.id)===e.target.value);if(t){$('#mission').value=t.mission;$('#hotelRate').value=t.hotel;$('#allowRate').value=t.allow;calcTravel()}};
function removeFund(id){let x=funds.find(x=>x.id===id);if(x&&confirm('ลบแหล่งเงินนี้หรือไม่? รายการเดิมจะยังเก็บชื่อแหล่งเงินไว้')){funds=funds.filter(x=>x.id!==id);logAudit('ลบ','แหล่งเงิน',x.name);save();render()}}window.removeFund=removeFund;function removePerson(id){let x=people.find(x=>x.id===id);if(x&&confirm('ลบบุคลากรนี้หรือไม่?')){people=people.filter(x=>x.id!==id);logAudit('ลบ','บุคลากร',x.name);save();render()}}window.removePerson=removePerson;function removeTemplate(id){let x=templates.find(x=>x.id===id);if(x&&confirm('ลบแม่แบบนี้หรือไม่?')){templates=templates.filter(x=>x.id!==id);logAudit('ลบ','แม่แบบ',x.name);save();render()}}window.removeTemplate=removeTemplate;
function restoreTrash(id){let i=trash.findIndex(x=>String(x.id)===String(id));if(i<0)return;let x=trash[i];if(x.kind==='transaction')tx.push(x.item);else if(x.kind==='debt')debts.push(x.item);else if(x.kind==='travel')travels.push(x.item);trash.splice(i,1);logAudit('กู้คืน',x.kind,x.item.detail||x.item.mission||x.item.name||'');save();render();toast('กู้คืนแล้ว')}window.restoreTrash=restoreTrash;function purgeTrash(id){if(confirm('ลบถาวรและไม่สามารถกู้คืนได้หรือไม่?')){trash=trash.filter(x=>String(x.id)!==String(id));save();render()}}window.purgeTrash=purgeTrash;
function csvDownload(name,rows){let csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('#exportAllCsvBtn').onclick=()=>csvDownload('transactions.csv',[['วันที่','ประเภท','เลขเอกสาร','รายละเอียด','หมวดหมู่','คู่ค้า','จำนวนเงิน'],...tx.map(x=>[x.date,x.type==='income'?'รายรับ':'รายจ่าย',x.docno,x.detail,x.category,x.party,x.amount])]);$('#exportCsvBtn').onclick=()=>csvDownload('audit-report.csv',[['วันเวลา','ผู้ใช้','การทำงาน','รายการ','รายละเอียด'],...audit.map(x=>[new Date(x.at).toLocaleString('th-TH'),x.user,x.action,x.item,x.detail])]);
function dateTH(s){if(!s)return'-';return new Date(s+'T00:00:00').toLocaleDateString('th-TH',{day:'2-digit',month:'short',year:'numeric'})}function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#category').innerHTML=categories.map(x=>`<option>${x}</option>`).join('');$('#categoryTags').innerHTML=categories.map(x=>`<span>${x}</span>`).join('');$('#date').value=new Date().toISOString().slice(0,10);$('#travelStart').value=$('#travelEnd').value=new Date().toISOString().slice(0,10);calcTravel();$('#today').textContent=new Date().toLocaleDateString('th-TH',{weekday:'long',day:'numeric',month:'long',year:'numeric'});render();

function updateNetStatus(){const e=document.getElementById('netStatus');if(!e)return;const on=navigator.onLine;e.textContent=on?'● ออนไลน์ — พร้อมซิงค์ Google Sheet':'● ออฟไลน์ — บันทึกในเครื่องและรอซิงค์';e.className='sync-status '+(on?'online':'offline')}window.addEventListener('online',updateNetStatus);window.addEventListener('offline',updateNetStatus);updateNetStatus();
