(()=>{
const ENDPOINT='https://script.google.com/macros/s/AKfycbwD9l8rOh2nv9iyex1PKekYsRuT2Sb4dCa2dS0JZvB_vgx3ncvz_EchemQinUm_cEOKHw/exec';
const MAP={'รายการ':'office_tx','ไปราชการ':'office_travels','บุคลากร':'office_people','ประวัติ':'office_audit'};
const status=()=>document.getElementById('netStatus'),say=t=>{const e=status();if(e)e.textContent=t};
async function post(tab,data){const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'upsert',tab,data})});if(!r.ok)throw Error('HTTP '+r.status)}
function rows(k){try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return []}}
function merge(a,b){const m=new Map();[...a,...b].forEach(x=>{if(x&&x.id!=null){const k=String(x.id),old=m.get(k);if(!old||String(x.updatedAt||x.at||'')>=String(old.updatedAt||old.at||''))m.set(k,x)}});return [...m.values()]}
function userRows(){try{return Object.entries(JSON.parse(localStorage.getItem('office_users')||'{}')).map(([name,v])=>({id:'user:'+name,name,password:v.password,role:v.role||'ผู้บันทึก',updatedAt:v.updatedAt||''}))}catch{return []}}
function saveUsers(remote){let u={};remote.forEach(x=>{if(x&&x.name)u[x.name]={password:x.password,role:x.role||'ผู้บันทึก',updatedAt:x.updatedAt||''}});if(remote.length)localStorage.setItem('office_users',JSON.stringify(u));window.dispatchEvent(new Event('office-users-synced'))}
async function sync(){if(!navigator.onLine){say('● ออฟไลน์ — บันทึกในเครื่องและรอซิงค์');return}say('● กำลังซิงค์ Google Sheet…');try{for(const [tab,key] of Object.entries(MAP))for(const row of rows(key))await post(tab,{...row,updatedAt:row.updatedAt||row.at||''});for(const u of userRows())await post('ผู้ใช้งาน',u);const r=await fetch(ENDPOINT+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const all=await r.json();for(const [tab,key] of Object.entries(MAP)){const remote=(all[tab]||[]).map(r=>{try{return typeof r[6]==='string'?JSON.parse(r[6]):r[6]}catch{return null}}).filter(Boolean);localStorage.setItem(key,JSON.stringify(merge(rows(key),remote)))}const ru=(all['ผู้ใช้งาน']||[]).map(r=>{try{return typeof r[6]==='string'?JSON.parse(r[6]):r[6]}catch{return null}}).filter(Boolean);saveUsers(ru);localStorage.setItem('office_last_sync',new Date().toISOString());say('● ซิงค์ Google Sheet แล้ว');if(typeof render==='function')render()}catch(e){console.warn('sync',e);say('● ออนไลน์ — ซิงค์ไม่สำเร็จ ข้อมูลยังอยู่ในเครื่อง')}}
window.officeSync=sync;window.addEventListener('online',sync);setTimeout(sync,1200);setInterval(sync,15000);
})();
